<script setup>
import {ref,computed,onMounted} from 'vue';import {useRoute} from 'vue-router';import BaseLayout from '../layout/BaseLayout.vue';import axios from '../../axiosInstance';import {salesError,tokenHeaders,shareUrl,downloadSales,productionLabels} from '../../models/sales';
const route=useRoute(),staff=computed(()=>!!route.params.orderId),token=new URLSearchParams(route.hash.slice(1)).get('token')??'';
const detail=ref(null),form=ref({status:'awaiting_artwork',production_due_at:'',delivery_due_at:'',materials:'',note:''}),file=ref(null),note=ref(''),name=ref(''),comment=ref(''),confirm=ref(false),error=ref(''),busy=ref(false),share=ref(''),uuid=ref(route.params.uuid);
async function run(fn){if(busy.value)return;busy.value=true;error.value='';try{await fn();}catch(e){error.value=salesError(e);}finally{busy.value=false;}}
async function load(){detail.value=(await axios.get(staff.value?'/orders/'+route.params.orderId+'/production':'/public-artworks/'+route.params.uuid,{headers:tokenHeaders(token)})).data;if(detail.value.production)form.value={...detail.value.production};uuid.value=detail.value.uuid??route.params.uuid;}
onMounted(()=>run(load));
function save(){return run(async()=>{await axios.put('/orders/'+route.params.orderId+'/production',form.value);await load();});}
function upload(){return run(async()=>{const data=new FormData();data.append('file',file.value);data.append('note',note.value);const result=(await axios.post('/orders/'+route.params.orderId+'/artworks',data)).data;share.value=shareUrl('grafika',result);await load();});}
function renew(){return run(async()=>{share.value=shareUrl('grafika',(await axios.post('/orders/'+route.params.orderId+'/artworks/share')).data);});}
function decision(action){return run(async()=>{await axios.post('/public-artworks/'+route.params.uuid+'/decision',{action,version:detail.value.versions[0].version,name:name.value,comment:comment.value,...(action==='approve'?{confirm:confirm.value}:{})},{headers:tokenHeaders(token)});await load();comment.value='';});}
const statuses={pending:'Čaká na schválenie',changes_requested:'Pripomienky zákazníka',approved:'Schválené'};
</script>
<template><BaseLayout><template #main><section class="col-span-12 max-w-4xl w-full mx-auto p-4 space-y-5"><h1 class="text-2xl font-semibold">Grafika a výroba {{detail?.serial_number}}</h1><p v-if="error" role="alert" class="text-red-700">{{error}}</p>
<template v-if="detail"><p v-if="detail.production">{{productionLabels[detail.production.status]}} · výroba do {{detail.production.production_due_at||'neurčené'}} · dodanie do {{detail.production.delivery_due_at||'neurčené'}}</p>
<template v-if="staff"><router-link :to="'/objednavky/'+route.params.orderId+'/show'" class="underline mr-4">Detail objednávky</router-link><router-link to="/predaj" class="underline">Prehľad výroby</router-link><form @submit.prevent="save" class="border rounded p-4 space-y-3"><h2 class="font-semibold">Plán zákazky</h2>
<label class="block">Stav<select v-model="form.status" class="border rounded ml-2"><option v-for="(label,key) in productionLabels" :key="key" :value="key">{{label}}</option></select></label>
<label class="block">Výroba do<input v-model="form.production_due_at" type="date" class="border ml-2"/></label><label class="block">Dodanie do<input v-model="form.delivery_due_at" type="date" class="border ml-2"/></label>
<label class="block">Materiály<input v-model="form.materials" maxlength="2000" class="block border w-full p-2"/></label><label class="block">Interná poznámka<textarea v-model="form.note" maxlength="5000" class="block border w-full p-2"/></label><button :disabled="busy" class="bg-blue-700 text-white rounded p-2">Uložiť plán</button></form>
<form @submit.prevent="upload" class="border rounded p-4 space-y-3"><h2 class="font-semibold">Nová verzia grafiky</h2><p>PDF, PNG, JPG alebo WebP do 10 MB. Nová verzia vyžaduje nové schválenie. Po začatí výroby už návrh nemožno nahradiť.</p><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" required @change="file=$event.target.files[0]"/><label class="block">Poznámka pre zákazníka<textarea v-model="note" class="block border w-full p-2"/></label><button :disabled="busy || !file" class="bg-blue-700 text-white rounded p-2">Nahrať návrh</button></form>
<button v-if="detail.versions.length" :disabled="busy" @click="renew" class="underline">Vytvoriť nový odkaz na schválenie (zneplatní starý)</button><label v-if="share" class="block">Odkaz pre zákazníka<input :value="share" readonly class="w-full border p-2" @focus="$event.target.select()"/></label></template>
<div v-for="(v,index) in detail.versions" :key="v.id" class="border rounded p-4 space-y-2"><h2 class="font-semibold">Verzia {{v.version}} {{index===0?'— aktuálna':'— nahradená'}}</h2><p>{{statuses[v.status]}}</p><button :disabled="busy" @click="run(()=>downloadSales('/public-artworks/'+uuid+'/files/'+v.version,v.name,token))" class="underline text-blue-700">Stiahnuť a skontrolovať {{v.name}}</button><p class="whitespace-pre-wrap">{{v.note}}</p><p v-if="v.approved_at">Schválil/a {{v.approved_by}} · {{new Date(v.approved_at).toLocaleString('sk-SK')}}</p><ul><li v-for="c in v.comments" :key="c.id" class="border-l pl-3 my-2"><strong>{{c.author}}</strong>: {{c.body}}</li></ul></div>
<form v-if="!staff && detail.versions.length && detail.versions[0].status!=='approved'" @submit.prevent="decision('approve')" class="border rounded p-4 space-y-3"><h2 class="font-semibold">Vyjadrenie k aktuálnej verzii</h2><label class="block">Vaše meno<input v-model="name" required maxlength="150" class="block border p-2"/></label><label class="block">Pripomienky<textarea v-model="comment" maxlength="5000" class="block w-full border p-2"/></label><button type="button" :disabled="busy || !name || !comment" @click="decision('comment')" class="underline">Odoslať pripomienky</button><label class="flex gap-2"><input v-model="confirm" required type="checkbox"/>Skontroloval/a som aktuálnu verziu a schvaľujem ju na výrobu.</label><button :disabled="busy" class="bg-green-700 text-white rounded p-3">Schváliť verziu {{detail.versions[0].version}}</button><p class="text-sm">Schválenie sa zaznamená s vaším menom a časom cez tento súkromný odkaz.</p></form>
</template></section></template></BaseLayout></template>
