<script setup>
import {ref,computed,onMounted} from 'vue';import {useRoute,useRouter} from 'vue-router';import BaseLayout from '../layout/BaseLayout.vue';import axios from '../../axiosInstance';import {salesError,tokenHeaders,shareUrl,downloadSales,quoteLabels} from '../../models/sales';
const route=useRoute(),router=useRouter(),staff=computed(()=>!!route.params.id),token=new URLSearchParams(route.hash.slice(1)).get('token')??'';
const quote=ref(null),error=ref(''),busy=ref(false),share=ref(''),name=ref(''),confirm=ref(false),methods=ref([]),search=ref(''),products=ref([]);
const form=ref({items:[],shipping_method_id:'',shipping_price:0,terms:'',valid_until:''});const latest=computed(()=>quote.value?.versions?.[0]);
const total=computed(()=>latest.value?latest.value.items.reduce((sum,i)=>sum+i.quantity*Number(i.price),Number(latest.value.shipping.price)):0);
async function run(fn){if(busy.value)return;busy.value=true;error.value='';try{await fn();}catch(e){error.value=salesError(e);}finally{busy.value=false;}}
async function load(){quote.value=(await axios.get(staff.value?'/sales-quotes/'+route.params.id:'/public-quotes/'+route.params.uuid,{headers:tokenHeaders(token)})).data;
 if(staff.value){const v=latest.value;form.value={items:(v?.items??quote.value.requested_items).map(i=>({variant_id:i.variant_id,name:i.snapshot?i.snapshot.name+' / '+(i.snapshot.variant_name??''):i.name,quantity:i.quantity,price:i.price??''})),shipping_method_id:v?.shipping.id??'',shipping_price:v?.shipping.price??0,terms:v?.terms??'',valid_until:v?.valid_until?.slice(0,10)??''};}}
onMounted(()=>run(async()=>{await load();if(staff.value)methods.value=(await axios.get('/shipping-methods')).data.data;}));
function offer(){return run(async()=>{await axios.post('/sales-quotes/'+quote.value.id+'/offer',{...form.value,version:quote.value.version});await load();});}
function accept(){return run(async()=>{const {data}=await axios.post('/public-quotes/'+quote.value.uuid+'/accept',{version:quote.value.version,name:name.value,confirm:confirm.value},{headers:tokenHeaders(token)});await router.push('/objednavka/'+data.order_uuid);});}
function getShare(){return run(async()=>{share.value=shareUrl('ponuka',(await axios.post('/sales-quotes/'+quote.value.id+'/share')).data);});}
function withdraw(){if(!window.confirm('Stiahnuť ponuku? Zákazník ju už nebude môcť prijať.'))return;return run(async()=>{await axios.post('/sales-quotes/'+quote.value.id+'/withdraw');await load();});}
function find(){return run(async()=>{products.value=(await axios.get('/homes',{params:{bySearchInput:search.value}})).data.data;});}
function add(p,v){form.value.items.push({variant_id:v.id,name:p.name+' / '+(v.name??''),quantity:Math.max(1,v.min_order??1),price:v.active_price});}
</script>
<template><BaseLayout><template #main><section class="col-span-12 max-w-4xl w-full mx-auto p-4 space-y-5">
<h1 class="text-2xl font-semibold">Cenová ponuka</h1><p v-if="error" role="alert" class="text-red-700">{{error}}</p>
<div v-if="quote" class="space-y-5"><p class="font-semibold">{{quoteLabels[quote.status]}} · č. {{quote.id}} · verzia {{quote.version}}</p>
<p v-if="!staff" class="rounded bg-blue-50 p-3">Uložte si túto adresu stránky. Obsahuje váš prístup k dopytu a prijatiu ponuky; zdieľajte ju len s oprávnenou osobou. Ponuku skontrolujte na tejto stránke po nacenení obsluhou.</p>
<p>{{quote.customer.company}} · {{quote.customer.name}} · {{quote.customer.email}}</p><p>{{quote.customer.street}}, {{quote.customer.postcode}} {{quote.customer.city}}</p><h2 class="font-semibold">Zadanie</h2><p class="whitespace-pre-wrap">{{quote.brief}}</p>
<ul><li v-for="file in quote.attachments" :key="file.id"><button @click="run(()=>downloadSales('/public-quotes/'+quote.uuid+'/files/'+file.id,file.name,token))" class="underline">{{file.name}}</button></li></ul>
<div v-if="latest" class="border rounded p-4 space-y-3"><h2 class="font-semibold">Ponuka verzie {{latest.version}}, platná do {{latest.valid_until.slice(0,10)}}</h2>
<table class="w-full text-left"><thead><tr><th>Položka</th><th>Množstvo</th><th>Cena / jednotku s DPH</th></tr></thead><tbody><tr v-for="(item,i) in latest.items" :key="i"><td>{{item.snapshot.name}} — {{item.snapshot.variant_name}}</td><td>{{item.quantity}} {{item.snapshot.unit_value}}</td><td>{{Number(item.price).toFixed(2)}} €</td></tr></tbody></table>
<p>Doprava: {{latest.shipping.name}} — {{Number(latest.shipping.price).toFixed(2)}} €</p><p class="font-semibold">Spolu s DPH: {{total.toFixed(2)}} €</p><p class="whitespace-pre-wrap">{{latest.terms}}</p></div>
<details v-if="quote.versions.length>1"><summary>Predchádzajúce verzie</summary><div v-for="v in quote.versions.slice(1)" :key="v.id" class="border p-3"><p>Verzia {{v.version}}, platnosť {{v.valid_until.slice(0,10)}} (nahradená)</p><p v-for="(i,n) in v.items" :key="n">{{i.snapshot.name}} / {{i.snapshot.variant_name}}: {{i.quantity}} × {{i.price}} €</p><p>Doprava {{v.shipping.name}}: {{v.shipping.price}} €</p><p>{{v.terms}}</p></div></details>
<router-link v-if="quote.order_uuid" :to="'/objednavka/'+quote.order_uuid" class="underline text-blue-700">Zobraziť vytvorenú objednávku</router-link>
<p v-if="quote.is_expired" class="text-red-700">Platnosť ponuky uplynula. Požiadajte obsluhu o novú verziu.</p>
<form v-if="!staff && quote.status==='offered' && !quote.is_expired" @submit.prevent="accept" class="space-y-3 border p-4"><label class="block">Vaše meno<input v-model="name" required maxlength="150" class="block rounded border p-2"/></label><label class="flex gap-2"><input v-model="confirm" required type="checkbox"/>Súhlasím s aktuálnou ponukou, cenou a podmienkami. Prijatím vytvorím záväznú objednávku.</label><button :disabled="busy" class="rounded bg-blue-700 text-white p-3">Prijať ponuku a objednať</button></form>
<div v-if="staff" class="space-y-4"><router-link to="/predaj" class="underline">Späť na ponuky a výrobu</router-link>
<div><button :disabled="busy" @click="getShare" class="underline">Vytvoriť nový odkaz pre zákazníka</button><p class="text-sm">Nový odkaz zneplatní predchádzajúci.</p><input v-if="share" :value="share" readonly aria-label="Odkaz pre zákazníka" class="w-full border p-2" @focus="$event.target.select()"/></div>
<template v-if="!['accepted','withdrawn'].includes(quote.status)"><h2 class="font-semibold">{{latest?'Nová verzia ponuky':'Nacenenie'}}</h2>
<form @submit.prevent="find" class="flex gap-2"><input v-model="search" placeholder="Vyhľadať tovar" aria-label="Vyhľadať tovar" class="border rounded p-2"/><button :disabled="busy">Hľadať</button></form>
<div v-for="p in products" :key="p.id"><p>{{p.name}}</p><button v-for="v in p.variants" :key="v.id" @click="add(p,v)" class="underline mr-3">Pridať {{v.name||v.code}}</button></div>
<form @submit.prevent="offer" class="space-y-3"><div v-for="(item,i) in form.items" :key="i" class="grid grid-cols-2 sm:grid-cols-4 gap-2 border-b pb-2"><p>{{item.name}}</p><label>Množstvo<input v-model.number="item.quantity" type="number" min="1" max="100000" required class="w-full border rounded"/></label><label>Cena s DPH<input v-model.number="item.price" type="number" min="0" step="0.01" required class="w-full border rounded"/></label><button type="button" @click="form.items.splice(i,1)" class="text-red-700">Odobrať</button></div>
<label class="block">Doprava<select v-model="form.shipping_method_id" required class="border rounded ml-2"><option value="">Vyberte</option><option v-for="m in methods" :key="m.id" :value="m.id">{{m.name}}</option></select></label>
<label class="block">Cena dopravy s DPH<input v-model.number="form.shipping_price" required type="number" min="0" step="0.01" class="border ml-2"/></label><label class="block">Platnosť do<input v-model="form.valid_until" required type="date" class="border ml-2"/></label><label class="block">Podmienky a termín<textarea v-model="form.terms" class="block w-full border rounded p-2"/></label>
<button :disabled="busy || !form.items.length" class="bg-blue-700 text-white rounded p-3 disabled:opacity-40">Uložiť a sprístupniť ponuku</button></form><button :disabled="busy" @click="withdraw" class="text-red-700">Stiahnuť ponuku</button></template></div></div>
</section></template></BaseLayout></template>
