<script setup>
import {ref,onMounted} from 'vue';import BaseLayout from '../layout/BaseLayout.vue';import axios from '../../axiosInstance';import {salesError,productionLabels,quoteLabels} from '../../models/sales';
const quotes=ref(null),production=ref(null),error=ref(''),busy=ref(false),overdue=ref(false),status=ref('');
async function load(q=1,p=1){if(busy.value)return;busy.value=true;error.value='';try{const [a,b]=await Promise.all([axios.get('/sales-quotes',{params:{page:q}}),axios.get('/production',{params:{page:p,overdue:overdue.value?1:0,status:status.value}})]);quotes.value=a.data;production.value=b.data;}catch(e){error.value=salesError(e);}finally{busy.value=false;}}
onMounted(()=>load());
</script>
<template><BaseLayout><template #main><section class="col-span-12 w-full p-4 space-y-5"><h1 class="text-2xl font-semibold">Ponuky a výroba</h1><p v-if="error" role="alert" class="text-red-700">{{error}}</p>
<h2 class="text-xl">Cenové dopyty a ponuky</h2><p v-if="quotes && !quotes.data.length">Zatiaľ žiadne dopyty.</p><div v-for="q in quotes?.data" :key="q.id" class="border rounded p-3"><router-link :to="'/predaj/ponuky/'+q.id" class="underline">#{{q.id}} — {{q.customer.company}}</router-link> · {{quoteLabels[q.status]}} · {{q.customer.email}}</div>
<div v-if="quotes?.last_page>1" class="flex gap-3"><button :disabled="busy || quotes.current_page===1" @click="load(quotes.current_page-1,production.current_page)">Predchádzajúca</button><span>{{quotes.current_page}} / {{quotes.last_page}}</span><button :disabled="busy || quotes.current_page===quotes.last_page" @click="load(quotes.current_page+1,production.current_page)">Ďalšia</button></div>
<h2 class="text-xl">Plán výroby</h2><p>Novú zákazku otvoríte cez „Grafika a plán výroby“ v detaile objednávky.</p><div class="flex gap-4"><label><input v-model="overdue" type="checkbox" @change="load(quotes?.current_page??1,1)"/> Iba omeškané</label><select v-model="status" @change="load(quotes?.current_page??1,1)" class="border"><option value="">Všetky stavy</option><option v-for="(label,key) in productionLabels" :key="key" :value="key">{{label}}</option></select></div>
<div v-for="p in production?.data" :key="p.id" class="border rounded p-3" :class="p.overdue?'border-red-500 bg-red-50':''"><router-link :to="'/vyroba/'+p.order_id" class="underline">{{p.serial_number}} — {{p.company}}</router-link><p>{{productionLabels[p.status]}} <strong v-if="p.overdue" class="text-red-700"> — Po termíne</strong></p><p>Výroba do {{p.production_due_at||'neurčené'}} · dodanie do {{p.delivery_due_at||'neurčené'}}</p><p>Materiál: {{p.materials||'neurčený'}}</p></div><p v-if="production && !production.data.length">Žiadne zákazky pre tento filter.</p>
<div v-if="production?.last_page>1" class="flex gap-3"><button :disabled="busy || production.current_page===1" @click="load(quotes.current_page,production.current_page-1)">Predchádzajúca</button><span>{{production.current_page}} / {{production.last_page}}</span><button :disabled="busy || production.current_page===production.last_page" @click="load(quotes.current_page,production.current_page+1)">Ďalšia</button></div>
</section></template></BaseLayout></template>
